vulncheck/home/urls.py
from django.urls import path
from home import views
app_name = 'home'
urlpatterns = [ 
    
    path('', views.home_login , name="login"),
    path('logout', views.home_logout ,name="logout"),
    path('profile', views.home_profile ,name="profile"),


]

vulncheck/vulncheck/urls.py
from django.contrib import admin
from django.urls import path
from home import urls as home_urls
from mainmenu import urls as mainmenu_urls
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dashboard import urls as dashboard_urls

urlpatterns = [
    path('home/', include(home_urls, namespace="home")),
    path('mainmenu/', include(mainmenu_urls, namespace="mainmenu")),
    path('dashboard/', include(dashboard_urls, namespace="dashboard")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'VULNCHECK'
admin.site.site_title = 'VULNCHECK'

vulncheck/home/models.py
from django.db import models

# Create your models here.

vulncheck/home/forms.py
from django import forms


class PasswordChangeForm(forms.Form):

    oldpass = forms.CharField(required=True , widget= forms.PasswordInput(
    attrs={
    
        "class":"form-control",
        "id":"oldpass",
    
        "placeholder":"Enter old password"
    }
    )) 

    newpass = forms.CharField(required=True , widget= forms.PasswordInput(
    attrs={
    
        "class":"form-control",
        "id":"newpass",

         "placeholder":"Enter new password"
    }
    )) 

    confirmpass = forms.CharField(required=True , widget= forms.PasswordInput(
    attrs={
    
        "class":"form-control",
        "id":"confirmpass",

         "placeholder":"Confirm password"
    }
    )) 

vulncheck/home/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import authenticate , login , logout
from django.contrib.auth.decorators import login_required , permission_required
from home.forms import PasswordChangeForm
from django.contrib.auth.models import User


# Create your views here.

def home_logout(request):
    logout(request)
    return redirect('/home')

def home_login(request):
    if request.method == "POST":

      user = authenticate(username=request.POST.get('username'),password = request.POST.get('password'))
      
      if(user is not None ):
        if(user.last_login == None):
          login(request , user)
          messages.add_message(request, messages.INFO, "Change your password!!")
          return redirect('/home/profile')
        else:
          login(request , user)
          return redirect('/dashboard')

      else:
    #    print(request.POST.get('password'))
         messages.add_message(request, messages.ERROR, 'invalid email or password')

    return render(request , "home/login.html" , {}) 

def home_profile(request):
    if request.method == "POST":
      form = PasswordChangeForm(request.POST)
      user = authenticate(username=request.POST.get('username'),password = request.POST.get('password'))
      
      if(form.is_valid()):
        data = form.cleaned_data
        
        user = authenticate(username=request.user.username,password = data['oldpass'])

        if(user is None ):
          messages.add_message(request, messages.ERROR, ' Old password is not correct')
          return redirect('/home/profile')
        elif(data['newpass'] != data['confirmpass']):
          messages.add_message(request, messages.ERROR, ' Passwords did not match')
          return redirect('/home/profile')
        else:
          u = User.objects.get(username=request.user.username)
          u.set_password(data['newpass'])
          u.save()
        messages.add_message(request, messages.INFO, ' Password changed successfully')
        return redirect('/home/profile')
     
    #   if(user is not None ):
    #      login(request , user)
    #      return redirect('/patient/list')
    #   else:
    # #    print(request.POST.get('password'))
    #      messages.add_message(request, messages.ERROR, 'invalid email or password')
    else:
      form = PasswordChangeForm()

    context = {
      'form' : form,
      'title' : 'Profile Information'
    }


    return render(request , "home/profile.html" , context) 

vulncheck/home/templates/home/login.html
<html lang="en"><head>
    {% load static %}
    <meta charset="utf-8">
    <title>Login | GA POSTING</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin &amp; Dashboard Template" name="description">
    <meta content="Themesdesign" name="author">
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static "admin/assets/images/favicon.ico">

    <!-- Bootstrap Css -->
    <link href="{% static "admin/assets/css/bootstrap.min.css" %}" rel="stylesheet" type="text/css">
    <!-- Icons Css -->
    <link href="{% static "admin/assets/css/icons.min.css" %}" rel="stylesheet" type="text/css">
    <!-- App Css-->
    <link href="{% static "admin/assets/css/app.min.css" %}" rel="stylesheet" type="text/css">

</head>

<body class="bg-primary bg-pattern">
    <div class="home-btn d-none d-sm-block">
        <a href="index.html"><i class="mdi mdi-home-variant h2 text-white"></i></a>
    </div>

    <div class="account-pages my-5 pt-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="text-center mb-5">
                        <a href="" class="logo"><img src="{% static "admin/assets/images/test123.png" %}" height="50" alt="logo"></a>
                        <h5 class="font-size-16 text-white-50 mb-4">VULNCHECK</h5>
                    </div>
                </div>
            </div>
            <!-- end row -->

            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card">
                        <div class="card-body p-4">
                            <div class="p-2">
                                <h5 class="mb-5 text-center">Sign in to continue to VULNCHECK.</h5>
                                <form class="form-horizontal" action="" method="POST">{% csrf_token %}

                                    <div class="row">
                                        
                                            {% if messages %}
                                            <ul class="messages">
                                                {% for message in messages %}
                                                {% if message.tags == 'info'%}
                                                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                            <span aria-hidden="true">×</span>
                                                        </button>
                                                        <strong>{{ message.tags }}: </strong>  {{ message }}.
                                                    </div>
                
                                                {% else %}

                                                <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
                                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>
                                                    <strong>{{ message.tags }}: </strong> {{ message }}
                                                </div>
                                                {% endif %}
                                                <!-- <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.tags }}</li> -->
                                                {% endfor %}
                                            </ul>
                                            {% endif %}
                                        <div class="col-md-12">
                                            <div class="form-group mb-4">
                                                <label for="username">Email</label>
                                                <input type="text" name="username" class="form-control" id="username" placeholder="Enter username">
                                            </div>
                                            <div class="form-group mb-4">
                                                <label for="userpassword">Password</label>
                                                <input type="password" name="password" class="form-control" id="userpassword" placeholder="Enter password">
                                            </div>

                                            
                                            <div class="mt-4">
                                                <button class="btn btn-success btn-block waves-effect waves-light" type="submit">Log In</button>
                                            </div>
                                        
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end row -->
        </div>
    </div>
    <!-- end Account pages -->

    <script src="{% static "admin/assets/libs/jquery/jquery.min.js" %}"></script>
    <script src="{% static "admin/assets/libs/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "admin/assets/libs/metismenu/metisMenu.min.js" %}"></script>
    <script src="{% static "admin/assets/libs/simplebar/simplebar.min.js" %}"></script>
    <script src="{% static "admin/assets/libs/node-waves/waves.min.js" %}"></script>

    <script src="{% static "admin/assets/js/app.js" %}"></script>   



</body></html>

vulncheck/home/templates/home/profile.html
{% extends "base.html" %}

{% load static %}
{% block header %}
    <link href="{% static "admin/assets/libs/bootstrap-datepicker/css/bootstrap-datepicker.min.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}



<div class="col-xl-12">
    <div class="card">
        <div class="card-body">

            <h4 class="header-title">{{request.user}}'s Profile</h4>
            

            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <!-- <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#home" role="tab" aria-selected="false">
                        <i class="dripicons-home mr-1 align-middle"></i> <span class="d-none d-md-inline-block">Home</span> 
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#profile" role="tab" aria-selected="false">
                        <i class="dripicons-user mr-1 align-middle"></i> <span class="d-none d-md-inline-block">Profile</span>
                    </a>
                </li> -->
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#messages" role="tab" aria-selected="true">
                        <i class="mdi mdi-lock font-size-16 align-middle mr-1"></i> <span class="d-none d-md-inline-block">Change Password</span>
                    </a>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#settings" role="tab">
                        <i class="dripicons-gear mr-1 align-middle"></i> <span class="d-none d-md-inline-block">Settings</span>
                    </a>
                </li> -->
            </ul>

            <!-- Tab panes -->
            <div class="tab-content p-3">
                <div class="tab-pane" id="home" role="tabpanel">
                    <p class="mb-0">
                        Raw denim you probably haven't heard of them jean shorts Austin.
                        Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache
                        cliche tempor, williamsburg carles vegan helvetica. Reprehenderit
                        butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi,
                        qui irure terry richardson ex squid. Aliquip placeat salvia cillum
                        iphone. Seitan aliquip quis cardigan american apparel, butcher
                        voluptate nisi qui.
                    </p>

                
    
                    <div class="form-group row">
                        <label for="example-search-input" class="col-md-2 col-form-label">Search</label>
                        <div class="col-md-10">
                            <input class="form-control" type="search" value="How do I shoot web" id="example-search-input">
                        </div>
                    </div>
                     
                    
                </div>
                <div class="tab-pane" id="profile" role="tabpanel">
                    <p class="mb-0">
                        Food truck fixie locavore, accusamus mcsweeney's marfa nulla
                        single-origin coffee squid. Exercitation +1 labore velit, blog
                        sartorial PBR leggings next level wes anderson artisan four loko
                        farm-to-table craft beer twee. Qui photo booth letterpress,
                        commodo enim craft beer mlkshk aliquip jean shorts ullamco ad
                        vinyl cillum PBR. Homo nostrud organic, assumenda labore
                        aesthetic magna delectus mollit.
                    </p>
                </div>
                <div class="tab-pane active" id="messages" role="tabpanel">
                  
                <div class="form-group mb-4">
                    
                    <label>{{ form.phone_number.label_tag }}</label>
                    <div class="input-group">
                        {{ form.phone_number }}
                        
                    </div>
                </div>
                    
                    <form action="{% url 'home:profile' %}" method="POST">{% csrf_token %}
                        <div class="form-group row">
                            {{ form.oldpass.errors }}
                            <label for="example-search-input" class="col-md-2 col-form-label">Old Password</label>
                            <div class="col-md-4">
                                {{ form.oldpass }}
                                
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ form.newpass.errors }}
                            <label for="example-search-input" class="col-md-2 col-form-label">New Password</label>
                            <div class="col-md-4">
                                {{ form.newpass }}
                              
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ form.confirmpass.errors }}
                            <label for="example-search-input" class="col-md-2 col-form-label">Confirm New Password</label>
                            <div class="col-md-4">
                                {{ form.confirmpass }}
                              
                            </div>
                        </div>

                        

                            <div class="col-auto">
                                
                                <div class="mt-3 mr-sm-2">
                                    <button type="submit" class="btn btn-primary mt-2">Change Password</button>
                                </div>
                            
                            </div>
                    </form>
                 
                </div>
                <div class="tab-pane" id="settings" role="tabpanel">
                    <p class="mb-0">
                        Trust fund seitan letterpress, keytar raw denim keffiyeh etsy
                        art party before they sold out master cleanse gluten-free squid
                        scenester freegan cosby sweater. Fanny pack portland seitan DIY,
                        art party locavore wolf cliche high life echo park Austin. Cred
                        vinyl keffiyeh DIY salvia PBR, banh mi before they sold out
                        farm-to-table VHS viral locavore cosby sweater. Lomo wolf viral,
                        mustache.
                    </p>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}


{% block footer %}
    <script src="{% static "admin/assets/libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js" %}"></script>
    <script src="{% static "admin/assets/js/pages/form-advanced.init.js" %}"></script>
    <script src="{% static "admin/assets/libs/bootstrap-maxlength/bootstrap-maxlength.min.js" %}"></script>
{% endblock %}