vulncheck/dashboard/urls.py
from django.urls import path
from dashboard import views
app_name = 'dashboard'
urlpatterns = [ 
    path('create', views.dashboard_index ,name="index"),
    path('libraries', views.dashboard_libraries ,name="libraries"),
    path('lib_scan/<int:lib_id>', views.library_scan , name="lib_scan"),
    path('vuln_check/<int:lib_id>', views.vuln_check , name="vuln_check"),
    path('delete_librabry/<int:librabry_id>', views.delete_librabry , name="delete_librabry"),
    path('cve_scan', views.cve_scan , name="cve_scan"),
    path('scan_all', views.scan_all , name="scan_all"),


    
 
]

vulncheck/home/urls.py
from django.urls import path
from home import views
app_name = 'home'
urlpatterns = [ 
    
    path('', views.home_login , name="login"),
    path('logout', views.home_logout ,name="logout"),
    path('profile', views.home_profile ,name="profile"),


]

vulncheck/vulncheck/urls.py
from django.contrib import admin
from django.urls import path
from home import urls as home_urls
from mainmenu import urls as mainmenu_urls
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dashboard import urls as dashboard_urls

urlpatterns = [
    path('home/', include(home_urls, namespace="home")),
    path('mainmenu/', include(mainmenu_urls, namespace="mainmenu")),
    path('dashboard/', include(dashboard_urls, namespace="dashboard")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'VULNCHECK'
admin.site.site_title = 'VULNCHECK'

vulncheck/dashboard/models.py
from django.db import models


class Library(models.Model):
    STATUS = (
        ('', '------------'),
        ('application', 'Application'),
        ('services', 'Services'),
        ('windows', 'Operating System: Windows'),
        ('linux', 'Operating System: Linux'),
        
    )

    application_name = models.CharField(default=None ,max_length=100)
    library_list = models.FileField(upload_to='uploads/')
    data_mode = models.CharField(blank=True , default='no' ,max_length=100 , choices = STATUS)
    created_at = models.DateField(default=None)
    updated_at = models.DateField(default=None)
    created_by = models.IntegerField(default=None)

    def __str__(self):
        return '%s' % self.application_name

class CVE_Scan(models.Model):
    

    cve_name = models.CharField(default=None ,max_length=100)


    def __str__(self):
        return '%s' % self.cve_name

vulncheck/dashboard/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator
from dashboard.models import Library ,CVE_Scan 

# model form 
from django.db import models
# from django.forms import ModelForm , Textarea , ModelChoiceField , Select  


class Library_Form(forms.ModelForm):

    class Meta:
        model = Library
        
        
        fields = ['application_name','library_list' ,'data_mode']

             
        widgets = {
            
            'application_name': forms.TextInput(attrs={
                "type" : "text",
                "class":"form-control"
            }),
            'library_list': forms.ClearableFileInput(attrs={
                "class":"form-control",
                "id":"picture",
                "type" : "file",
            }),
            'data_mode': forms.Select(attrs={
                "type" : "text",
                "class":"form-control custom-select",
                "id":"data_mode"
            }),
           
        }


class  CVE_Scan_Form(forms.ModelForm):
    class Meta:
        model = CVE_Scan
        
        
        fields = ['cve_name']

             
        widgets = {
            
            'cve_name': forms.TextInput(attrs={
                "type" : "text",
                "class":"form-control"
            }),
         
           
        }

vulncheck/dashboard/views.py
from django.shortcuts import render
import calendar
from datetime import datetime
from django.contrib.auth.decorators import login_required , permission_required
from pypi_simple import PyPISimple 
from dashboard.forms import Library_Form , CVE_Scan_Form
from dashboard.models import  Library
from django.contrib import messages
from django.utils import timezone
from django.urls import reverse
from django.http import HttpResponseRedirect
import vulners  
from django.core.mail import send_mail


# @login_required
# def dashboard_index(request):

    
    
#     url = "dashboard/index.html"    
#     with PyPISimple() as client:
#         requests_page = client.get_project_page('requests')
#     requests_page = client.get_project_page('requests')
#     pkg = requests_page.packages[0]
#     print(pkg.version)
    
#     context = {
#         'title': pkg.version,
       
        
      
#     }

#     return render(request , url , context) 

@login_required
def dashboard_index(request):
    form = None
    url = "dashboard/index.html" 
    if request.method == 'POST':
        form = Library_Form(request.POST, request.FILES)
        if(form.is_valid()):
            data = form.save(commit=False)
            data.created_at = timezone.now()
            data.updated_at = timezone.now()
            data.created_by = request.user.id
            data.save()
            messages.add_message(request, messages.INFO, 'Application Libraries stored successful')
            return HttpResponseRedirect(reverse('dashboard:libraries'))
     
    else:
        form = Library_Form()
    
    context = {
        
        'title': "Add Libraries",
        'form':form
        
    } 
     
    return render(request , url , context)

@login_required
def dashboard_libraries(request):
    libraries = Library.objects.all().order_by('-id')
    url = "dashboard/list_librabries.html" 
    # send_mail(
    #     'Payment',
    #     'find payment.',
    #     'kidkudzy@gmail.com',
    #     ['kmakufa@outlook.com', 'promiseksystems@gmail.com'],
    #     fail_silently=False,
    # )
    context = {
        
        'title': "Add Libraries",
        'libraries':libraries
        
    } 


    return render(request , url , context)



@login_required
def library_scan(request ,lib_id=None):
    library = Library.objects.filter(id=lib_id).order_by('-id')
    f = open(library[0].library_list.path, "r")
    print("------------------")

    lines = f.readlines()
    for line in lines:
        print(line)
    print("------------------")
    f.close()
    context = {
        "item":library[0], 
        "lines":lines
    }
    return render(request, 'dashboard/library_view.html', context)
    
@login_required
def scan_all(request ):

    url_path = "dashboard/scan_all.html"

    library = Library.objects.filter(data_mode="application").order_by('-id').first()
    print(library.data_mode)
    f = open(library.library_list.path, "r")
    print("------------------")
    lines = f.readlines()



    data = []
    Issues = []
    Affected_Cve = []


    for line in lines:
        # here comes the vuln scanner logic
        sep = '=='
        stripped = line.split(sep, 1)[0]
        lib_version = line.split(sep, 1)[1]
        is_safe = False
        
        # print(line.strip())
        # print("-------without end-------")
        # print(line.split(sep, 1)[0])
        # print("------with end-----")
        
        # check updates and security
        with PyPISimple() as client:
            requests_page = client.get_project_page(stripped.strip())
        
        requests_page = client.get_project_page(stripped.strip())
        pkg_params = {}

        if(library.data_mode == 'application'):
            

            try:
                try:
                    vulners_api = vulners.Vulners(api_key="4QIYDKA0NXPHUWXJNQYLISIZEZZH8FM25YNK0L518VOWJJEOWO81XGMH2KSL81KJ")
                    results = vulners_api.softwareVulnerabilities(stripped.strip(), lib_version.strip())
                    # print(len(stripped.strip()))
                    # print(len(lib_version.strip()))
                    # results = vulners_api.softwareVulnerabilities("httpd", "1.3")
                    exploit_list = results.get('exploit')
                    vulnerabilities_list = [results.get(key) for key in results if key not in ['info', 'blog', 'bugbounty']]
                    print("vulneralibity type_____"+vulnerabilities_list[0][0]['type'])
                    print(vulnerabilities_list[0][0]['title'])
                    Issues = vulnerabilities_list[0][0]
                    

                except:
                    is_safe = True
                    print("safe")
                pkg = requests_page.packages[0]
                pkg_params = {"name":pkg.project , "current_version":lib_version.strip() , "latest_version":pkg.version ,"digest":pkg.get_digests()['sha256'] , 'url':pkg.url ,'is_signed':pkg.has_sig ,'is_safe':is_safe ,'issue_title':Issues}
            except:
                pkg_params = {"name":stripped.strip() , "current_version":lib_version.strip() , "latest_version":"n/a" ,"digest":"n/a",'is_safe':is_safe ,'issue_title':Issues}

             # scan safety-db
            
        data.append(pkg_params.copy())
        # print(data)



    # application level 
    # 
    # 
    # 
    # 
    # 
    # 


    library = Library.objects.filter(data_mode="windows").order_by('-id').first()
    print(library.data_mode)
    f = open(library.library_list.path, "r")
    print("------------------")
    lines = f.readlines()



    windows = []
    Issues = []
    Affected_Cve = []
    

    for line in lines:
        # here comes the vuln scanner logic
        sep = '=='
        stripped = line.split(sep, 1)[0]
        lib_version = line.split(sep, 1)[1]
        is_safe = False
        
        # print(line.strip())
        # print("-------without end-------")
        # print(line.split(sep, 1)[0])
        # print("------with end-----")
        
        # check updates and security
        with PyPISimple() as client:
            requests_page = client.get_project_page(stripped.strip())
        
        requests_page = client.get_project_page(stripped.strip())
        windows_pkg_params = {}

        if(library.data_mode == 'windows'):
        

            try:
                vulners_api = vulners.Vulners(api_key="4QIYDKA0NXPHUWXJNQYLISIZEZZH8FM25YNK0L518VOWJJEOWO81XGMH2KSL81KJ")
                win_vulners = vulners_api.kbAudit(os="Windows Server 2012 R2", kb_list=[lib_version.strip()])
                need_2_install_kb = win_vulners['kbMissed']
                affected_cve = win_vulners['cvelist']
                print("_____affected cve_____")
                print(affected_cve[0])
                Affected_Cve = affected_cve

            except:
                is_safe = True
                
            windows_pkg_params = {"name":stripped.strip() , "kb_name":lib_version.strip() , "latest_version":"n/a" ,"digest":"n/a",'is_safe':is_safe ,'affected_cve':Affected_Cve}
            #  scan safety-db
            
        windows.append(windows_pkg_params.copy())
        # print(data)


    # f = open(library[0].library_list.path, "r")
    # print("------------------")

    # lines = f.readlines()

    # data = []
    # Issues = []
    # Affected_Cve = []
    # url_path = ""
   
    # for line in lines:
    #     # here comes the vuln scanner logic
    #     sep = '=='
    #     stripped = line.split(sep, 1)[0]
    #     lib_version = line.split(sep, 1)[1]
    #     is_safe = False
        
    #     # print(line.strip())
    #     # print("-------without end-------")
    #     # print(line.split(sep, 1)[0])
    #     # print("------with end-----")
      
    #     # check updates and security
    #     with PyPISimple() as client:
    #         requests_page = client.get_project_page(stripped.strip())
        
    #     requests_page = client.get_project_page(stripped.strip())
    #     pkg_params = {}

    #     if(library[0].data_mode == 'application'):
    #         url_path = "dashboard/app_vulncheck.html"

    #         try:
    #             try:
    #                 vulners_api = vulners.Vulners(api_key="4QIYDKA0NXPHUWXJNQYLISIZEZZH8FM25YNK0L518VOWJJEOWO81XGMH2KSL81KJ")
    #                 results = vulners_api.softwareVulnerabilities(stripped.strip(), lib_version.strip())
    #                 # print(len(stripped.strip()))
    #                 # print(len(lib_version.strip()))
    #                 # results = vulners_api.softwareVulnerabilities("httpd", "1.3")
    #                 exploit_list = results.get('exploit')
    #                 vulnerabilities_list = [results.get(key) for key in results if key not in ['info', 'blog', 'bugbounty']]
    #                 print("vulneralibity type_____"+vulnerabilities_list[0][0]['type'])
    #                 print(vulnerabilities_list[0][0]['title'])
    #                 Issues = vulnerabilities_list[0][0]
                    

    #             except:
    #                 is_safe = True
    #                 print("safe")
    #             pkg = requests_page.packages[0]
    #             pkg_params = {"name":pkg.project , "current_version":lib_version.strip() , "latest_version":pkg.version ,"digest":pkg.get_digests()['sha256'] , 'url':pkg.url ,'is_signed':pkg.has_sig ,'is_safe':is_safe ,'issue_title':Issues}
    #         except:
    #             pkg_params = {"name":stripped.strip() , "current_version":lib_version.strip() , "latest_version":"n/a" ,"digest":"n/a",'is_safe':is_safe ,'issue_title':Issues}

    #          # scan safety-db
            
    #     elif(library[0].data_mode == 'services'):
    #         url_path = "dashboard/service_vulncheck.html"
    #         pkg_params = {"name":stripped.strip() , "current_version":lib_version.strip() , "latest_version":"n/a" ,"digest":"n/a" ,'is_safe':is_safe}
            
    #     elif(library[0].data_mode == 'windows'):

vulncheck/dashboard/templates/dashboard/_modal_kb_data.html
                                  
                                                        
<!--  Modal content for the above example -->
<div class="modal fade bs-example-modal-lg" id="modal_{{item.name}}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title mt-0" id="myLargeModalLabel">Affected CVE for {{item.kb_name}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
     
                {% for cve in item.affected_cve %}
                    <div class="row">
                        <div class="col-sm-4">
                            CVE
                        </div>
                        <div class="col-sm-4">
                     
                            {{cve}}
                        </div>
                        <div class="col-sm-4">
                     
                            <button class="btn btn-sm btn-outline">Get Detailed Info</button>
                        </div> 

                    </div>
                 {% endfor %}
                

            

               
                <hr>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal --> 

vulncheck/dashboard/templates/dashboard/admin.html
{% extends "base.html" %}

{% block content%}
<div class="row">
    <div class="col-sm-6 col-xl-3">
        <div class="card">
            <div class="card-body">
                <div class="media">
                    <div class="media-body">
                        <h5 class="font-size-14">Total Patients  </h5>
                    </div>
                    <div class="avatar-xs">
                        <span class="avatar-title rounded-circle bg-primary">
                            <i class="dripicons-box"></i>
                        </span>
                    </div>
                </div>
                <h4 class="m-0 align-self-center">{{patient.count}} Patient(s)</h4>
               
                <p class="mb-0 mt-3 text-muted"><span class="text-success"><i class="mdi mdi-eye"></i><a href=""> View more</a></span></p>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-xl-3">
        <div class="card">
            <div class="card-body">
                <div class="media">
                    <div class="media-body">
                        <h5 class="font-size-14">Total Doctors</h5>
                    </div>
                    <div class="avatar-xs">
                        <span class="avatar-title rounded-circle bg-primary">
                            <i class="dripicons-briefcase"></i>
                        </span>
                    </div>
                </div>
                <h4 class="m-0 align-self-center">{{doctor}} Doctor(s)</h4>
                <p class="mb-0 mt-3 text-muted"><span class="text-success"><i class="mdi mdi-eye"></i><a href=""> View more</a></span></p>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-xl-3">
        <div class="card">
            <div class="card-body">
                <div class="media">
                    <div class="media-body">
                        <h5 class="font-size-14">Tx Cards </h5>
                    </div>
                    <div class="avatar-xs">
                        <span class="avatar-title rounded-circle bg-primary">
                            <i class="dripicons-tags"></i>
                        </span>
                    </div>
                </div>
                <h4 class="m-0 align-self-center">{{tx_card.count}} Tx Card(s)</h4>
                <p class="mb-0 mt-3 text-muted"><span class="text-success"><i class="mdi mdi-eye"></i><a href=""> View more</a></span></p>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-xl-3">
        <div class="card">
            <div class="card-body">
                <div class="media">
                    <div class="media-body">
                        <h5 class="font-size-14">Blank</h5>
                    </div>
                    <div class="avatar-xs">
                        <span class="avatar-title rounded-circle bg-primary">
                            <i class="dripicons-cart"></i>
                        </span>
                    </div>
                </div>
                <h4 class="m-0 align-self-center">0</h4>
                <p class="mb-0 mt-3 text-muted"><span class="text-success"><i class="mdi mdi-eye"></i><a href=""> View more</a></span></p>
            </div>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

             
                <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead>
                    <tr>
                        
                        <th>First Name </th>
                        <th>Last Name</th>
                        <th>Phone Number</th>
                        <th>Doctor</th>
                        <th>Gender  </th>
                        <th>Status  </th>
                        <th>Actions  </th>
                        
                    
                    </tr>
                    </thead>


                    <tbody>
                 
                    {% for item in patient %}
                        <tr>
                            <td>{{item.first_name}}</td>
                            <td>{{item.last_name}}</td>
                            <td>{{item.phone_number}}</td>
                            <td>{{item.doctor}}</td>
                             <td>{{item.gender}}</td>
                            <td>{{item.status}}</td>
                           
                        
                        
                            <td>
                                <a href="{% url  'patient:view' item.id  %}" class="btn btn-outline-primary waves-effect waves-light" >Details </a>
                                <a href="{% url  'patient:edit' item.id  %}" class="btn btn-outline-success waves-effect waves-light" >Edit</a>
                                <a href="{% url  'patient:list_patients_cards' item.id  %}" class="btn btn-outline-primary waves-effect waves-light" >Tx Cards</a>
                                <a href="{% url  'patient:delete' item.id  %}" class="btn btn-outline-danger waves-effect waves-light" onclick="alert('Are you sure you want to delete')" >Delete</a>
                                
                              
                            </td>
                        
                        </tr>
                    {% endfor %}
               
              
                    </tbody>
                </table>

            </div>
        </div>
    </div> <!-- end col -->

</div> <!-- end row -->

{% endblock %}

vulncheck/dashboard/templates/dashboard/app_vulncheck.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="row">
  <div class="col-12">
      
    
   
  </div>
</div>
    <div class="row">
        <div class="col-md-6">
            <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                <thead>
                <tr>
                    
                    <th>Library Name </th>
                    
                    <th>Installed Version</th>
                    {% comment %} <th>Latest Version</th> {% endcomment %}
                    <th>Digest </th>
                    <th>Url </th>
                    <th>Is Signed </th>
                    <th>Is Safe </th>
                    <th>Actions  </th>
                    
                
                </tr>
                </thead>


                <tbody>
             
                {% for item in data %}
                
                    <tr>
                        <td>{{item.name}}</td>
                    
                        
                        <td>{{item.current_version}}</td>
                        {% comment %} <td>{{item.latest_version}}</td> {% endcomment %}
                        <td>{{item.digest}}</td>
                        <td>
                           <a href="{{item.url}}">{{item.name}}</a> 
                        </td>
                        <td> 
                            {% if item.is_signed == None %}
                            <p class="text-warning">Unspecified</p>
                            {% else %}
                            <p class="text-success">Signed</p>
                            {% endif %}
                        </td>

                       
                            {% if item.is_safe %}
                             <td> <p class="text-success">Safe</p></td>
                             
                            {% else %}
                            
                            <td><p class="text-danger">Vulnerable</p></td>
                            
                            <td>
                              <a data-toggle="modal" data-target="#modal_{{item.name}}" class="btn btn-sm btn-outline-success waves-effect waves-light"><i class="fas fa-eye"></i></a>|
                            {% comment %} <button class="btn btn-sm btn-primary"> Issues</button> {% endcomment %}
                            </td>
                            {% include './issues.html' %}
                            {% endif %}
                        

                    
                       
                    
                    
                      
                    
                    </tr>
                {% endfor %}
           
          
                </tbody>
            </table>

        </div>
       
      </div>



  {% endblock %}

vulncheck/dashboard/templates/dashboard/cve_results.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

    <div class="row">
        <div class="col-md-12">
                <div class="row">
                    <div class="col-sm-4">
                       ID
                    </div>
                    <div class="col-sm-8">
                        {{cve_data.id}}
                    </div>
                </div>

        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
                <div class="row">
                    <div class="col-sm-4">
                       Score
                    </div>
                    <div class="col-sm-8">
                        {{cve_data.cvss.score}}
                    </div>
                </div>

        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
                <div class="row">
                    <div class="col-sm-4">
                       Description
                    </div>
                    <div class="col-sm-8">
                        {{cve_data.description}}
                    </div>
                </div>

        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
                <div class="row">
                    <div class="col-sm-4">
                       Affected Software
                    </div>
                    <div class="col-sm-8">
                        {% for afsoft in cve_data.affectedSoftware %}
                        <div class="row">
                            <div class="col-4">
                            CPN NAME
                            </div>
                            <div class="col-8">
                            {{afsoft.cpeName}}
                            </div>
                        </div>
                         <div class="row">
                            <div class="col-4">
                            NAME
                            </div>
                            <div class="col-8">
                            {{afsoft.name}}
                            </div>
                        </div>
                         <div class="row">
                            <div class="col-4">
                            Version
                            </div>
                            <div class="col-8">
                            {{afsoft.version}}
                            </div>
                        </div>
                        <hr>
                        {% endfor %}
                    </div>
                </div>

        </div>
    </div>



    

    



  {% endblock %}

vulncheck/dashboard/templates/dashboard/library_view.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="row">
  <div class="col-12">
      
      <!-- <a href="#" class="btn btn-success float-right"></a> -->
   
  </div>
</div>
    <div class="row">
        <div class="col-md-6">
          <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                
            <tbody>
             
              <tr>
                <td><b>Application Name  </b> </td>
                <td>
                    <a href="{{item.library_list.path}}">{{item.application_name}}</a>
                    </td>
              </tr>

              {% for item in lines %}
                        <tr>
                            <td>{{item}}</td>
         
                        </tr>
                    {% endfor %}
    

            </tbody>
          </table>
        </div>
       
      </div>



  {% endblock %}

vulncheck/dashboard/templates/dashboard/list_librabries.html
{% extends "base.html" %}

{% load static %}
{% block header %}
    <link href="{% static "admin/assets/libs/bootstrap-datepicker/css/bootstrap-datepicker.min.css" %}" rel="stylesheet">
    <style>
        input[type="text"]:disabled {
        background: #dddddd;
}
    </style>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-12">
        
        <a href="{% url 'dashboard:index' %}" class="btn btn-lg btn-success float-right">Add Libraries</a>
     
    </div>
    <br>
</div>



<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

             
                <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead>
                    <tr>
                        
                        <th>Application Name </th>
                        <th>Type </th>
                        <th>Library list</th>
                        <th>Mode</th>
                        <th>Actions  </th>
                        
                    
                    </tr>
                    </thead>


                    <tbody>
                 
                    {% for item in libraries %}
                        <tr>
                            <td>{{item.application_name}}</td>
                            <td>{{item.data_mode}}</td>
                            <td>{{item.library_list}}</td>
                            <td>{{item.data_mode}}</td>
                        
                           
                        
                        
                            <td>
                                <a href="{% url  'dashboard:lib_scan' item.id  %}" class="btn btn-outline-primary waves-effect waves-light" >View Contents</a>
                                <a href="{% url  'dashboard:vuln_check' item.id  %}" class="btn btn-outline-primary waves-effect waves-light" >Scan Application</a>
                                <a href="#" class="btn btn-outline-success waves-effect waves-light" >Edit</a>
                                <a href="{% url  'dashboard:delete_librabry' item.id %}" class="btn btn-outline-danger waves-effect waves-light" onclick="alert('Are you sure you want to delete')" >Delete</a>
                               
                            </td>
                 {% endfor %}        
                        </tr>
                   
               
              
                    </tbody>
                </table>

            </div>
        </div>
    </div> <!-- end col -->

</div> <!-- end row -->

{% endblock %}
    
{% block footer %}


  
<!-- datetime -->
<script src="{% static "admin/assets/libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js" %}"></script>
<script src="{% static "admin/assets/js/pages/form-advanced.init.js" %}"></script>
<script src="{% static "admin/assets/libs/bootstrap-maxlength/bootstrap-maxlength.min.js" %}"></script>
     <!-- Required datatable js -->
     <script src="{% static "admin/assets/libs/datatables.net/js/jquery.dataTables.min.js" %}"></script>
     <script src="{% static "admin/assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js" %}"></script>

     <!-- Datatable init js -->
     <script src="{% static "admin/assets/js/pages/datatables.init.js" %}"></script>
{% endblock %}

vulncheck/dashboard/templates/dashboard/service_vulncheck.html
{% extends 'base.html' %}

{% block content %}
{% load static %}




  {% endblock %}